version: "2"
services:
  ux:
    build: ./src/ux/
    ports: 
      - "3000:3000"
  srv:
    build: ./src/srv/
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"